model_dir: run/

data:
  train_features_file: src-train.txt
  train_labels_file: tgt-train.txt
  eval_features_file: src-val.txt
  eval_labels_file: tgt-val.txt

  source_vocabulary: sp_src_vocab.txt
  target_vocabulary: sp_tgt_vocab.txt

  # for alignment model
  train_alignments: train-alignment.txt

  source_tokenization:
    type: SentencePieceTokenizer
    params:
      model: sp-src.model
      
  target_tokenization: 
    type: SentencePieceTokenizer
    params:
      model: sp-tgt.model
  
train:
  #train_steps: 500
  batch_size: 32
  max_step: 10000
  save_checkpoints_steps: 100
  keep_checkpoint_max: 4
#   eval:
#     external_evaluators: BLEU
# infer:
#     batch_size: 32
    
eval:
  batch_size: 32
  # (optional) Evaluate every this many steps (default: 5000).
  steps: 100
  scorers: bleu
  export_on_best: bleu
  export_format: ctranslate2
  max_exports_to_keep: 5
    
early_stopping:
    # (optional) The target metric name (default: "loss").
  metric: bleu
    # (optional) The metric should improve at least by this much to be considered
    # as an improvement (default: 0)
  min_improvement: 0.01
  steps: 100